name: Compile document

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: sudo apt install texlive-latex-base texlive-latex-extra

      # compile
      - name: Compile
        run: pdflatex main.tex
          
      - name: Rename
        run: mv main.pdf HOBO_Report.pdf
          
      - name: add and commit
        uses: EndBug/add-and-commit@latest
        with:
          add: HOBO_Report.pdf
          message: Compiled tex to PDF
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
